<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="10.2.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ApiCache.Application\ApiCache.Application.csproj" />
    <ProjectReference Include="..\ApiCache.Helper\ApiCache.Helper.csproj" />
    <ProjectReference Include="..\ApiCache.Infrastructure\ApiCache.Infrastructure.csproj" />
  </ItemGroup>

</Project>
